// **DO NOT EDIT, CHANGES WILL BE LOST** - automatically generated by ModuleReflectionGenerator at 2023-03-06T23:31:23.922937100
package tech.kzen.auto.client.codegen

import tech.kzen.lib.common.reflect.ReflectionRegistry
import tech.kzen.lib.common.reflect.ModuleReflection
import tech.kzen.auto.client.objects.document.common.DefaultAttributeEditor
import tech.kzen.lib.common.model.locate.ObjectLocation
import tech.kzen.auto.client.objects.document.feature.FeatureController
import tech.kzen.auto.client.objects.document.script.command.ScriptCommander
import tech.kzen.auto.client.objects.document.script.command.StepCommander
import tech.kzen.auto.client.objects.document.script.step.display.control.MappingCommander
import tech.kzen.auto.client.objects.document.script.step.StepController
import tech.kzen.auto.client.objects.document.script.step.display.StepDisplayWrapper
import tech.kzen.auto.client.objects.document.sequence.step.SequenceStepController
import tech.kzen.auto.client.objects.document.sequence.step.display.SequenceStepDisplayWrapper
import tech.kzen.auto.client.objects.ribbon.RibbonGroup
import tech.kzen.auto.client.objects.ribbon.RibbonTool


@Suppress("UNCHECKED_CAST")
object KzenAutoJsModule: ModuleReflection {
    override fun register(reflectionRegistry: ReflectionRegistry) {
reflectionRegistry.put(
    "tech.kzen.auto.client.objects.document.common.DefaultAttributeEditor\$Wrapper",
    listOf("objectLocation")
) { args ->
    DefaultAttributeEditor.Wrapper(args[0] as ObjectLocation)
}

reflectionRegistry.put(
    "tech.kzen.auto.client.objects.document.feature.FeatureController\$Wrapper",
    listOf("archetype")
) { args ->
    FeatureController.Wrapper(args[0] as ObjectLocation)
}

reflectionRegistry.put(
    "tech.kzen.auto.client.objects.document.script.command.ScriptCommander",
    listOf("stepCommanders")
) { args ->
    ScriptCommander(args[0] as List<StepCommander>)
}

reflectionRegistry.put(
    "tech.kzen.auto.client.objects.document.script.step.display.control.MappingCommander",
    listOf("stepArchetype", "itemArchetype")
) { args ->
    MappingCommander(args[0] as ObjectLocation, args[1] as ObjectLocation)
}

reflectionRegistry.put(
    "tech.kzen.auto.client.objects.document.script.step.StepController\$Wrapper",
    listOf("stepDisplays", "handle")
) { args ->
    StepController.Wrapper(args[0] as List<StepDisplayWrapper>, args[1] as StepController.Handle)
}

reflectionRegistry.put(
    "tech.kzen.auto.client.objects.document.script.step.StepController\$Handle",
    listOf()
) {
    StepController.Handle()
}

reflectionRegistry.put(
    "tech.kzen.auto.client.objects.document.sequence.step.SequenceStepController\$Wrapper",
    listOf("stepDisplays", "handle")
) { args ->
    SequenceStepController.Wrapper(args[0] as List<SequenceStepDisplayWrapper>, args[1] as SequenceStepController.Handle)
}

reflectionRegistry.put(
    "tech.kzen.auto.client.objects.document.sequence.step.SequenceStepController\$Handle",
    listOf()
) {
    SequenceStepController.Handle()
}

reflectionRegistry.put(
    "tech.kzen.auto.client.objects.ribbon.RibbonGroup",
    listOf("title", "archetype", "children")
) { args ->
    RibbonGroup(args[0] as String, args[1] as ObjectLocation, args[2] as List<RibbonTool>)
}

reflectionRegistry.put(
    "tech.kzen.auto.client.objects.ribbon.RibbonTool",
    listOf("delegate")
) { args ->
    RibbonTool(args[0] as ObjectLocation)
}
    }
}
