const val kotlinVersion = "1.5.0"
const val jvmTargetVersion = "16"
const val shadowVersion = "7.0.0"
const val springBootVersion = "2.4.5"
const val dependencyManagementVersion = "1.0.11.RELEASE"


//const val kzenLibVersion = "0.23.0-SNAPSHOT"
const val kzenLibVersion = "0.22.1"


const val logbackVersion = "1.2.3"
const val jacksonModuleKotlin = "2.12.2"
const val seleniumVersion = "3.141.59"
const val commonsCompressVersion = "1.20"
const val fastutilVersion = "8.5.4"
const val bifurcanVersion = "0.2.0-alpha6"
const val h2Version = "1.4.200"
const val zeroAllocationHashingVersion = "0.12"
const val disruptorVersion = "3.4.4"
const val bloomFilterVersion = "0.9.0"
const val commonsIoVersion = "2.8.0"


const val reactVersion = "17.0.2"
const val inlineStylePrefixerVersion = "6.0.0"
const val styledComponentsVersion = "5.2.3"
const val kotlinxDatetimeVersion = "0.2.0"
const val kotlinxHtmlVersion = "0.7.3"
const val lodashVersion = "4.17.21"
const val cropperJsVersion = "1.5.11"
const val materialUiCoreVersion = "4.11.3"
const val materialUiIconsVersion = "4.11.2"
const val materialUiLabVersion = "4.0.0-alpha.57"
const val reactSelectVersion = "4.3.0"

const val wrapperKotlinVersion = "pre.154-kotlin-1.5.0"
const val kotlinReactVersion = "17.0.2-$wrapperKotlinVersion"
const val kotlinReactDomVersion = "17.0.2-$wrapperKotlinVersion"
const val kotlinStyledVersion = "5.2.3-$wrapperKotlinVersion"
const val kotlinExtensionsVersion = "1.0.1-$wrapperKotlinVersion"
const val kotlinCssVersion = "1.0.0-$wrapperKotlinVersion"
