

ProjectController:
  abstract: true
  class: tech.kzen.auto.client.objects.ProjectController$Wrapper
  sidebarController: SidebarController
  ribbonController: RibbonController
  stageController: StageController


###########################################################


SidebarController:
  class: tech.kzen.auto.client.objects.sidebar.SidebarController$Wrapper
  meta:
    documentArchetypes:
      is: List
      of: Document
      by: Autowired


###########################################################


RibbonController:
  class: tech.kzen.auto.client.objects.ribbon.RibbonController.Wrapper
  meta:
    actionTypes:
      is: List
      of: ObjectLocation
      by: AutowiredNominal
      for: Action
    ribbonGroups:
      is: List
      of: RibbonGroup
      by: Autowired


RibbonGroup:
  abstract: true
  is: ChildContainer
  class: tech.kzen.auto.client.objects.ribbon.RibbonGroup
  title: ''
  documentArchetype: Document
  meta:
    title: String
    children:
      is: List
      of: RibbonTool
      by: ParentChild


RibbonTool:
  abstract: true
  is: ParentPointer
  class: tech.kzen.auto.client.objects.ribbon.RibbonTool
  meta:
    delegate:
      is: ObjectLocation
      by: Nominal


###########################################################


StageController:
  class: tech.kzen.auto.client.objects.document.StageController.Wrapper
  meta:
    documentControllers:
      is: List
      of: DocumentController
      by: Autowired


DocumentController:
  abstract: true
  is: ReactWrapper
  attributeController: AttributeController
  meta:
    type: Document
