

ProjectController:
  abstract: true
  class: tech.kzen.auto.client.objects.ProjectController$Wrapper
  sidebarController: SidebarController
#  ribbonController: RibbonController
  headerController: HeaderController
  stageController: StageController


###########################################################


SidebarController:
  class: tech.kzen.auto.client.objects.sidebar.SidebarController$Wrapper
  meta:
    archetypes:
      is: List
      of: Document
      by: AutowiredNominal


###########################################################


RibbonController:
  class: tech.kzen.auto.client.objects.ribbon.RibbonController$Wrapper
  meta:
    actionTypes:
      is: List
      of: ObjectLocation
      by: AutowiredNominal
      for: Action
    ribbonGroups:
      is: List
      of: RibbonGroup
      by: Autowired


RibbonGroup:
  abstract: true
  is: ChildContainer
  class: tech.kzen.auto.client.objects.ribbon.RibbonGroup
  title: ''
  archetype: Document
  meta:
    title: String
    children:
      is: List
      of: RibbonTool
      by: ParentChild
    archetype:
      is: Document
      by: Nominal


RibbonTool:
  abstract: true
  is: ParentPointer
  class: tech.kzen.auto.client.objects.ribbon.RibbonTool
  meta:
    delegate:
      is: ObjectLocation
      by: Nominal


###########################################################


HeaderController:
  class: tech.kzen.auto.client.objects.ribbon.HeaderController$Wrapper
  meta:
    documentControllers:
      is: List
      of: DocumentController
      by: Autowired


StageController:
  class: tech.kzen.auto.client.objects.document.StageController$Wrapper
  meta:
    documentControllers:
      is: List
      of: DocumentController
      by: Autowired


DocumentController:
  abstract: true
  is: ReactWrapper
  class: tech.kzen.auto.client.objects.document.DocumentController
  meta:
    archetype:
      is: Document
      by: Nominal
