
###########################################################

ReactWrapper:
  abstract: true
  class: tech.kzen.auto.client.api.ReactWrapper

###########################################################

ProjectController:
  abstract: true
  class: tech.kzen.auto.client.objects.ProjectController$Wrapper
  ribbonController: RibbonController
  sidebarController: SidebarController
  stageController: StageController
  meta:
    ribbonController: RibbonController
    sidebarController: SidebarController
    stageController: StageController


###########################################################

root:
  is: ProjectController

